recon-all -s ldrc_ldrc_c_040 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_c_043 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_c_044 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_c_045 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_c_046 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_c_047 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_c_054 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_c_057 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_c_058 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_c_059 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
