recon-all -autorecon2 -s ldrc_ldrc2_0_135 -sd /corral-repl/utexas/ldrc/FREESURFER/ 
recon-all -autorecon2 -s ldrc_ldrc2_0_137 -sd /corral-repl/utexas/ldrc/FREESURFER/ 
recon-all -autorecon2 -s ldrc_ldrc2_0_140 -sd /corral-repl/utexas/ldrc/FREESURFER/
recon-all -autorecon2 -s ldrc_ldrc2_0_143 -sd /corral-repl/utexas/ldrc/FREESURFER/ 
recon-all -autorecon2 -s ldrc_ldrc2_0_145 -sd /corral-repl/utexas/ldrc/FREESURFER/ 
recon-all -autorecon2 -s ldrc_ldrc2_0_151 -sd /corral-repl/utexas/ldrc/FREESURFER/
recon-all -autorecon2 -s ldrc_ldrc2_0_172 -sd /corral-repl/utexas/ldrc/FREESURFER/ 
recon-all -autorecon2 -s ldrc_ldrc_2_027 -sd /corral-repl/utexas/ldrc/FREESURFER/ 
recon-all -autorecon2 -s ldrc_ldrc_2_031 -sd /corral-repl/utexas/ldrc/FREESURFER/
recon-all -autorecon2 -s ldrc_ldrc_2_031_second -sd /corral-repl/utexas/ldrc/FREESURFER/
