recon-all -autorecon2 -s ldrc_ldrc_2_008 -sd /corral-repl/utexas/ldrc/FREESURFER/ 
recon-all -autorecon2 -s ldrc_ldrc_2_010 -sd /corral-repl/utexas/ldrc/FREESURFER/ 
recon-all -autorecon2 -s ldrc_ldrc_2_010_second -sd /corral-repl/utexas/ldrc/FREESURFER/
recon-all -autorecon2 -s ldrc_ldrc_2_010_third -sd /corral-repl/utexas/ldrc/FREESURFER/ 
recon-all -autorecon2 -s ldrc_ldrc2_0_104 -sd /corral-repl/utexas/ldrc/FREESURFER/ 
recon-all -autorecon2 -s ldrc_ldrc_2_011 -sd /corral-repl/utexas/ldrc/FREESURFER/
recon-all -autorecon2 -s ldrc_ldrc2_0_122 -sd /corral-repl/utexas/ldrc/FREESURFER/ 
recon-all -autorecon2 -s ldrc_ldrc2_0_123 -sd /corral-repl/utexas/ldrc/FREESURFER/ 
recon-all -autorecon2 -s ldrc_ldrc2_0_124 -sd /corral-repl/utexas/ldrc/FREESURFER/
recon-all -autorecon2 -s ldrc_ldrc2_0_128 -sd /corral-repl/utexas/ldrc/FREESURFER/
