recon-all -s ldrc_ldrc_1_004 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_0_013_second -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_1_002 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_1_004_second -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_1_007 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_1_015_second -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_1_020_second -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_1_015 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_1_020 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_1_028 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
