recon-all -s ldrc_ldrc_2_008_third -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_0_013_third -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_2_003_third -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_2_034_third -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_c_083 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_2_005_third -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_1_001_third -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_c_085 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_c_086 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_1_004_third -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
