recon-all -s ldrc_ldrc_1_036_second -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_2_003 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_2_005 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_2_005_second -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_2_008 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_2_008_second -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_2_010_second -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_2_010 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_2_011 -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
recon-all -s ldrc_ldrc_1_028_second -sd /corral-repl/utexas/ldrc/FREESURFER/ -all
